### ISSUE TITLE
Problems when I installing inet dsme

### ISSUE THREAD

**Issue by ghost** [openDSME/inet-dsme#1]
I have saw a video tutorial on youtube about openDSME and how install it. I have done the same process and when I am doing the building I got some errors. Mainly in the function receiveSignal. Could you give me some  recomendations about the installation and tell me if the currently version is stable? Or if you need more information?

**Comment by koalo** [comment]
We are currently restructuring the repositories so the videos are unfortunately not up-to-date. I will contact you again tomorrow with details.

**Comment by ghost** [comment]
Thanks

El 7/03/2018 3:10 p.m., Florian Kauer <notifications@github.com> escribió:

We are currently restructuring the repositories so the videos are unfortunately not up-to-date. I will contact you again tomorrow with details.

**Comment by koalo** [comment]
I updated the repositories. Please repeat the process shown in the videos from the beginning and check if any issues still exist. Please note that you need at least version OMNeT++ 5.3 (can be currently found under test versions at the OMNeT++ download page).

**Comment by ghost** [comment]
Thanks, it's working well, now I have a question, I understand that openDSME implement the standard IEEE 802.15.4 DSME. So, we want to work with the last amendment for the MAC sublayer of this standard. The question is, ¿What features do you have implemented of the standard ieee 802.15.4e?

**Comment by koalo** [comment]
That sounds great! Most features of the 2015 version of the IEEE 802.15.4 DSME are implemented, including channel adaption and channel hopping. However, there are some special primitives such as "DSME GTS change" that are not implemented that we think are not essential for the functionality (e.g. you could deallocate and allocate again if you want to change the GTS, of course with a higher overhead). So in the end you should be able to simulate a fully functional DSME network. If you have any further questions, please open a new issue or contact me via mail.

**Comment by nicklf3nick** [comment]
> That sounds great! Most features of the 2015 version of the IEEE 802.15.4 DSME are implemented, including channel adaption and channel hopping. However, there are some special primitives such as "DSME GTS change" that are not implemented that we think are not essential for the functionality (e.g. you could deallocate and allocate again if you want to change the GTS, of course with a higher overhead). So in the end you should be able to simulate a fully functional DSME network. If you have any further questions, please open a new issue or contact me via mail.

Hi koalo,
I had the same problem, and i using OMNET++ 6 and the latest version of inet.
However, there still exist "receiveSignal" problem when i build the project.

Can you give me some suggestions?
