### ISSUE TITLE
gtsallocation.ini file missing

### ISSUE THREAD

**Issue by haideraliawan** [openDSME/inet-dsme#2]
I did not find the "gtsallocation.ini " file in openDSME/inet-dsme repository? I am using latest version of openDSME/inet-dsme.

**Comment by koalo** [comment]
I do not know which file you mean. Why do you need it?

**Comment by haideraliawan** [comment]
I am working on IEEE 802.15.4 DSME protocol. I have omnet++p4 simulation environment to run openDSME. Which is implemented in the openDSME/inet-dsme. For this, I need a file gtsallocation.ini, which is not available in th latest version of openDSME/inet-dsme repository.

**Comment by koalo** [comment]
Why do you need this file? Is there any error message that says this file is required?

**Comment by haideraliawan** [comment]
I have to look at the code and everything as i have to work with th GTS allocation part of the DSME. I am a beginner, and new in wireless sensor networking area.

**Comment by koalo** [comment]
There is no gtsallocation.ini that is required for this. Please have a look at the Youtube Tutorial for getting started.

**Comment by haideraliawan** [comment]
I didn't find any youtube tutorial for getting started

**Comment by koalo** [comment]
https://www.youtube.com/watch?v=Xr6_5Ht2fIE&list=PLucSPeJjMBgwOgIRB1GKiST__vPgwd2tQ&index=3

**Comment by haideraliawan** [comment]
Thanks.

If you see in the tutorial, there is a "gte-allocation.ini" right after the
"example.ini" in the simulations directory. I do not have this
gts-allocation.ini in my openDSME/inet-dsme repository.

**Comment by koalo** [comment]
Oh, that one is deprecated. You can use evaluation.ini instead, but if you really need that file you can find it here: https://github.com/openDSME/inet-dsme/blob/e03032ebe216eaaf1ed10cd17544aa6103ee3e0e/simulations/gts-allocation.ini

**Comment by haideraliawan** [comment]
thank you so much for all you help :)

**Comment by koalo** [comment]
You are welcome

**Comment by haideraliawan** [comment]
one more question , how to include this file in openDSME/inet-dsme
directory?

**Comment by koalo** [comment]
Open a new file, copy the content into this file, then save it at openDSME/inet-dsme.

**Comment by haideraliawan** [comment]
Hi,

i am working on IEEE80215.4 DSME in omnet++. I want to run the example
evaluation.ini in inet-dsme, but i get some errors.

First error is in the file DSMEStationaryMobolity.cc which is:

Define_Module(DSMEStationaryMobility);
"invalid new-expression of abstract class type inet::DSMEStaionaryMobility"

second error is when run the evaluation.ini,I get the following message:

Class "inet_dsme::inet_dsme::StaticConcentricWrappingMobility" not found --
perhaps its code was not linked in, or the class wasn't registered with
Register_Class(), or in the case of modules and channels, with
Define_Module()/Define_Channel() -- in module (omnetpp::cModule)
Net802154MultiGateway.host[0] (id=2), during network setup"


Can u please guide me to resolve these issues?




"

**Comment by koalo** [comment]
These modules are not available in the current version of inet-dsme. Please update to the current version.

**Comment by haideraliawan** [comment]
is there any example of gts part of the DSME in the current version of
inet-dsme?

**Comment by koalo** [comment]
All provided examples use guaranteed time slots.

**Comment by haideraliawan** [comment]
Hi;

i am working on IEEE80215.4 DSME in omnet++. I want to run the example
evaluation.ini in inet-dsme.

My question is can I change the number of channels that is fixed in the  "
dsme_settings.h" file as follows:


constexpr uint8_t MAX_CHANNELS = 16;

and I also want to change the values of these expressions:

constexpr uint8_t MIN_SO = 1;
constexpr uint8_t MAX_BO = 10;
constexpr uint8_t MAX_MO = 9;

please guide me how can i change these values.

**Comment by koalo** [comment]
You usually do not want to change the MAX values, because they only specify the size of the data structures. So unless you want to save memory, these values should stay the same.

To change the SO, MO and BO, you can add the line `**.host[*].wlan[*].mac.multiSuperframeOrder = 6` (or superframeOrder or beaconOrder) to the omnetpp.ini

If you want to change the channels to be used, you have to modify the code here: https://github.com/openDSME/inet-dsme/blob/a52f09670ce0a72c9ace79a708bbab108208f899/src/DSMEPlatform.cc#L135

**Comment by haideraliawan** [comment]
can i also set the channel value= 2 in the omnetpp.ini ?

**Comment by koalo** [comment]
I do not see a channel value parameter in any of the ini files.

**Comment by haideraliawan** [comment]
So what if i want to do an experiment with number of channels = 2?
I can only modify the code in "DSMEPlatform.cc" to change the channels to
be used?

**Comment by koalo** [comment]
Yes

**Comment by haideraliawan** [comment]
Thank u so much .


I am trying to run my example but getting the following errors.

Simulation terminated with exit code: 136
Working directory:
/home/kiran/omnetpp-5.3p4/opendsme_workspace/inet-dsme/simulations
Command line: opp_run -m -n
.:../src:../../inet/src:../../inet/examples:../../inet/tutorials:../../inet/showcases
--image-path=../../inet/images -l ../src/inet-dsme -l ../../inet/src/INET
example.ini

Environment variables:
PATH=/home/kiran/omnetpp-5.3p4/bin::/home/kiran/bin:/home/kiran/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH=/home/kiran/omnetpp-5.3p4/lib::/home/kiran/omnetpp-5.3p4/opendsme_workspace/inet-dsme/src:/home/kiran/omnetpp-5.3p4/opendsme_workspace/inet/src:
OMNETPP_IMAGE_PATH=/home/kiran/omnetpp-5.3p4/images

I set the parameters value in the example.ini as follows:

[Config DSME]
**.host[*].wlan[*].macType = "DSME"
**.host[*].wlan[*].mac.macDSMEGTSExpirationTime = 7
**.host[0].wlan[*].mac.isPANCoordinator = true
**.host[*].wlan[*].mac.macCapReduction = false
**.host[*].wlan[*].mac.multiSuperframeOrder = 1
**.host[*].wlan[*].mac.superframeOrder = 2
**.host[*].wlan[*].mac.beaconOrder = 3

**Comment by koalo** [comment]
The MO always has to be larger than or equal to the SO (otherwise a superframe would be longer than a multi-superframe).

**Comment by haideraliawan** [comment]
i was running the example and the simulation stopped in the middle with an
error :

<!> Tag 'inet::PacketProtocolTag' is absent -- in module
(inet::physicallayer::RadioMedium) Net802154.radioMedium (id=27), at
t=0.12288s, event #3301

An i am also getting warnings in the INET code. for example :

generic.gnp.procDelay = default(2ms); (Here I see a warning message '
generic.gnp.procDelay': undefined parameter) in the
inet-dsme.simulation.IEEE802154EaxmpleHost.ned file.

 wlan[*].typename = default("WirelessInterface");
 wlan[*].radioType = default("Ieee802154NarrowbandScalarRadio");
('wlan[*].typename : undefined parameter)


Please Help me on this.

**Comment by koalo** [comment]
Please try the new versions of the inet and inet-dsme repository.

**Comment by haideraliawan** [comment]
Thanks.

I want to calculate Energy and throughput in inet-dsme, Can you please
specify how can I do that in inet-dsme ??

**Comment by koalo** [comment]
That depends on your actual definition of throughput, but you can easily extend for example the PRRTrafGen.ned to calculate this (read about ResultRecorders in OMNeT++). Energy was not yet considered, but you should also be able to measure it by adding an INET energy storage to your nodes.

**Comment by haideraliawan** [comment]
Hi,

Is it possible to reserved the gts slot for specific transmission?  For
example, I want that node1 transmit to node2  in timeslot 1. Moreover,
Where exactly in the code I can change or manipulate the gts part of DSMe?

Thanks,

**Comment by koalo** [comment]
This is the task of the scheduling. Add your own scheduling to this directory https://github.com/openDSME/openDSME/tree/master/dsmeAdaptionLayer/scheduling and let it create GTSSchedulingDecisions at your preference.

**Comment by haideraliawan** [comment]
The default scheduling is "TPS" for dsme and PIDcheduling  is also there.
I just wanted to know both TPS and PIDscheduling are two different
scheduling strategies for gts allocation?

**Comment by koalo** [comment]
Yes they are.

**Comment by haideraliawan** [comment]
Is there any option to track or follow the code when we start a simulation?

**Comment by koalo** [comment]
Yes, you can use the OMNeT++ debugger: https://docs.omnetpp.org/tutorials/tictoc/part2/#23-debugging Also please be advised we made some changes and bugfixes to the code base, so please pull those changes.

**Comment by haideraliawan** [comment]
Thanks for the reply.

So I have to download the updated version of inet-dsme?

**Comment by koalo** [comment]
Yes

**Comment by haideraliawan** [comment]
Hi,

I downloaded the new version of inet and inet-dsme. But when I build the
project, I see the following errors:

Error: NED package 'inet.tutorials.wireless' in feature 'wirelesstutorial'
was not found.
opp_featuretool: Error: NED package 'inet.tutorials.visualization' in
feature 'visualizationtutorial' was not found.
opp_featuretool: Error: NED package 'inet.tutorials.configurator' in
feature 'configuratortutorial' was not found.
opp_featuretool: Error: NED package 'inet.showcases.general' in feature
'generalshowcases' was not found.
opp_featuretool: Error: NED package 'inet.showcases.visualizer' in feature
'visualizershowcases' was not found.
opp_featuretool: Error: NED package 'inet.showcases.wireless' in feature
'wirelessshowcases' was not found.

**Comment by koalo** [comment]
This is since you have not pulled the showcases and tutorials submodules of inet. However, since you do not need them you do not have to worry.

**Comment by haideraliawan** [comment]
Hi,

I want to see what is being transferred over gts allocation. I want to see
what are the contents of a DSME message? because there is also some
transmission in the CAP too? When I run the simulation for example.ini,
evaluate results and see the NumUpperPacketsForCAP statistic, I get values
for the packets transmitted....

**Comment by koalo** [comment]
Yes, you can for example print the messages when they are sent to the physical layer.

**Comment by haideraliawan** [comment]
You mean that log file that we see during the simulation time ?

**Comment by koalo** [comment]
No, you have to add C++ code to output this data

**Comment by haideraliawan** [comment]
can you please specify the file name where exactly i can do that.

**Comment by koalo** [comment]
This can for example be implemented like this line:
https://github.com/openDSME/inet-dsme/blob/d8c773b3bdcbec6fa349cda9e0db974582fdfc3e/src/DSMEPlatform.cc#L300

**Comment by haideraliawan** [comment]
Hi,

In the example.ini, we specify 100 packets. In the results, we get for
example around 500 value for numUpperPacketsForGTS. Is it transmitting  100
packets over a period of time repeatedly? I don't have a clear idea on
that. And can you please specify what is the numUpperPacketsForGTS? Are
they GTS transmission or somthing?

Thanks!

**Comment by haideraliawan** [comment]
Hi,

In the example.ini, we specify 100 packets. In the results, we get for
example around 500 value for numUpperPacketsForGTS. Is it transmitting  100
packets over a period of time repeatedly? I don't have a clear idea on
that. And can you please specify what is the numUpperPacketsForGTS? Are
they GTS transmission or somthing? Also what is numUpperPacketsForCAP.?

Thanks!

**Comment by haideraliawan** [comment]
Hi,

In the example.ini, we specify 100 packets. In the results, we get for
example around 500 value for numUpperPacketsForGTS. Is it transmitting  100
packets over a period of time repeatedly? I don't have a clear idea on
that. And can you please specify what is the numUpperPacketsForGTS? Are
they GTS transmission or somthing? Also what is numUpperPacketsForCAP.?

Thanks!

**Comment by koalo** [comment]
Have a look at the code where these statistics are generated. That should help you to understand these metrics.

**Comment by haideraliawan** [comment]
Hi,

To calculate the throughput, I have to add the formula inPRRTrafGen.ned ??
And I can aslo records the the results in this file.

Thanks!

**Comment by haideraliawan** [comment]
Hi,

 I want to change the values of Bo, MO to calculate throughput in
inet-dsme.? And please specify that where can add the equation to calculate
throughput?

Thanks.

**Comment by koalo** [comment]
For this you can use set the parameters superframeOrder, multiSuperframeOrder and beaconOrder. The throughput can be calculated by counting the number of packets and divide this value by the measurement time.

**Comment by haideraliawan** [comment]
Hi,

Thanks for the reply. I have two questions.

1) I have defined the throughput related parameters in class PRRTrafGen. I
am computing the throughput value in its
"RRTrafGen::handleMessage(omnetpp::cMessage *msg)" function. Is this the
correct place to compute the throughput?

2) How to reflex the computation of throughput in dsme.anf analysis file?
In other words, how do we connect the dsme.anf analysis file with the
computed throughput parameters or any other user-defined parameters. I
believe, we have to change something in "PRRTrafGen.ned" file. If yes, can
you please specify the procedure to do it? Otherwise, please tell us how to
do it?

Finally, thanks for your help in advance.

Regards,
Kiran Ali

**Comment by koalo** [comment]
These questions are not about openDSME, but OMNeT++ in general. Please have a look at the OMNeT++ and INET documentation and tutorials.

**Comment by haideraliawan** [comment]
Hi,

My question is :
Can we alter the number of Available GTSs slots ? And cn you specify the
file name where can i make the changes in the code ??

**Comment by koalo** [comment]
You can add a line like `**.host[*].wlan[*].mac.multiSuperframeOrder = 6` to your ini file

**Comment by haideraliawan** [comment]
Thanks for the reply.

When i change the values of  SO, MO, BO in the configuration file the
simulation crashes  in the middle. I do not get a specific error msg. For
some values of BO, SO and MO the simulation runs successfully but when I
try to do the experiments by changing values of MO,BO, SO, it does not run
and I get error. For example for the following values of BO,SO  and SO, the
simulation does not run successfully.


****.host[*].wlan[*].mac.superframeOrder = 0
**.host[*].wlan[*].mac.multiSuperframeOrder = 1
**.host[*].wlan[*].mac.baconOrder = 6

Thanks

**Comment by koalo** [comment]
Of course. With SO=0 the slot is far to short for the packet transmission.

**Comment by haideraliawan** [comment]
Hi,

I have a question about static gts schedule in openDSME. Can we fix or
dedicate a time slot for specific nodes to transmit?  For example,  if host
1 wants to allocate a GTS with host 2 in a preferred slot, how can I
implement that and which part of the code do I need to change in openDSME?

Regards,
Kiran

**Comment by haideraliawan** [comment]
Hi,

In GTSScheduling.cc, there is a parameter "randomSlotID " in
GTSSchedulingDecision( ) function. I changed that parameter with a
staticSlotID =2 in GTSSchedulingDecision( ) function. This is just an
experiment for a static schedule. I want just two nodes host 1 and host 2
and I want that gts slotId 2 is to be assigned to them. ButI am not sure
where I could implement this schedule. I would be grateful for your help.

Thanks.

**Comment by flmeyer** [comment]
Hi, 

I just implemented a static scheduler which reads the schedule from an XML file (e.g. https://github.com/openDSME/inet-dsme/blob/master/simulations/static_schedule.xml). To use it, you have to set to set "scheduling" to "STATIC" in you omnetpp.ini and provide a valid XML file with the schedule by setting `**.host[*].wlan[*].mac.staticSchedule = xmldoc("file.xml")`. Good luck!

**Comment by haideraliawan** [comment]
Thanks you so much. Should I have to set "scheduling" to "STATIC" in my
omnetpp.ini? Because this parameter can be set in DSME.ned as "string
scheduling = default("STATIC");". Moreover, I provided a valid XML file
with the schedule by setting **.host[*].wlan[*].mac.staticSchedule =
xmldoc("static_schedule.xml") but the simulation crashes in the middle.

**Comment by flmeyer** [comment]
You can adjust the settings in the _omnetpp.ini_ or the _DSME.ned_ file. The difference is that the _DSME.ned_ file defines default values. Therefore, one should always overwrite a setting in the _omnetpp.ini_ to change them. 

Which schedule did you use? The _static_schedule.xml_ file is just an example that you can use to create your own static schedule. If you look into the file you can see that only two nodes are used and that there is only one slot setup for communication between them. If you use a network with more nodes for which the schedule is not defined, the simulation is likely to crash (still needs some adequate error message)

**Comment by haideraliawan** [comment]
Hi,

I need to download the older version of Inet (Inet 3.6.3) for omnetpp
5.2.1. Can you please send me the link to download the development of the
old INET 3.6.3 branch.

Thanks!
