### ISSUE TITLE
Error: Cannot load library '../src//libinet-dsme.dll':

### ISSUE THREAD

**Issue by syed-abdullah786** [openDSME/inet-dsme#3]
i am working on omnet++ and try to run this simulation code but it ends with error "Error: Cannot load library '../src//libinet-dsme.dll':" and it cannot run the simulation......Help me to overcome through this problem

**Comment by koalo** [comment]
You seem to use Windows. We have never tested this with Windows, so please use Linux, preferably Ubuntu.
