### ISSUE TITLE
Errors in building inet-dsme

### ISSUE THREAD

**Issue by 11187162** [openDSME/inet-dsme#5]
I have followed the video tutorial to import inet-dsme. However, after building I am getting the following errors:
I am using OMNeT++6 pre11 in ubuntu 18.04.

Errors

In file included from ./dsme_platform.h:96:
./DSMEPlatform.h:104:83: error: unknown type name 'intval_t'; did you mean 'inet::intval_t'?
    virtual void receiveSignal(cComponent *source, omnetpp::simsignal_t signalID, intval_t l, cObject *details) override;
                                                                                  ^~~~~~~~
                                                                                  inet::intval_t
/home/fafroz/Downloads/omnetpp-6.0pre11-src-linux/omnetpp-6.0pre11/include/omnetpp/simkerneldefs.h:81:17: note: 'inet::intval_t' declared here
typedef int64_t intval_t;
                ^
In file included from DSMEMessage.cc:44:
In file included from ./dsme_platform.h:96:
./DSMEPlatform.h:104:18: warning: 'dsme::DSMEPlatform::receiveSignal' hides overloaded virtual function [-Woverloaded-virtual]
    virtual void receiveSignal(cComponent *source, omnetpp::simsignal_t signalID, intval_t l, cObject *details) override;
                 ^
../../inet/src/inet/linklayer/base/MacProtocolBase.h:87:18: note: hidden overloaded virtual function 'inet::MacProtocolBase::receiveSignal' declared here: type mismatch at 3rd parameter ('omnetpp::cObject *' vs 'inet::intval_t' (aka 'long'))
    virtual void receiveSignal(cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override;
                 ^
1 warning and 1 error generated.
make[1]: *** [../out/clang-debug/src/DSMEMessage.o] Error 1
Makefile:162: recipe for target '../out/clang-debug/src/DSMEMessage.o' failed
make[1]: Leaving directory '/home/fafroz/opendsme_workspace/inet-dsme/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
"make MODE=debug all" terminated with exit code 2. Build might be incomplete.

13:12:35 Build Failed. 5 errors, 1 warnings. (took 6s.537ms)

Would you please suggest the solution?

Thank you.

**Comment by nicklf3nick** [comment]
Did you fixed it?

**Comment by 11187162** [comment]
No, actually I switched into other project. Thank you.

**Comment by nicklf3nick** [comment]
Thanks you.
BTW, can i contact you by email ? I also have some question.
